name: Deploy PHP App

on:
  push:
    branches:
      - main

jobs:
  ftps-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy via FTPS
        uses: ad-m/github-push-action@v0.6.0
        with:
          server: ${{ secrets.FTPS_HOST }}
          username: ${{ secrets.FTPS_USERNAME }}
          password: ${{ secrets.FTPS_PASSWORD }}
          port: 21
          local-dir: ./
          remote-dir: /public_html/
